// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrHj6e0-OosUx5d8qzkkfCehcT9tOvQm0',
    appId: '1:199733170254:android:bdead482ef837b1cb8b31f',
    messagingSenderId: '199733170254',
    projectId: 'request-ticket-f0db9',
    databaseURL:
        'https://request-ticket-f0db9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'request-ticket-f0db9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6NxpZ3nGdOuouSQltmeGHiKhZQxQMEHo',
    appId: '1:199733170254:ios:f26c5be509376184b8b31f',
    messagingSenderId: '199733170254',
    projectId: 'request-ticket-f0db9',
    databaseURL:
        'https://request-ticket-f0db9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'request-ticket-f0db9.appspot.com',
    iosClientId:
        '199733170254-qoh2biu5768dlihctt9glrr4j23ttk9d.apps.googleusercontent.com',
    iosBundleId: 'com.imt.request.ticket',
  );
}
